; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _carModelNames

._carModelNames
defb @01000001, @01110101, @01110011, @01110100
defb @01101001, @01101110, @00100000, @01000001
defb @01101100, @01101100, @01100101, @01100111
defb @01110010, @01101111, @00000000
