; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _palette1

._palette1
defb @00010000, @00000000, @00000010, @11000000
defb @11000010, @00011000, @00011010, @11011000
defb @11011010, @00000000, @00000011, @11100000
defb @11100011, @00011100, @00011111, @11111100
defb @11111111
