; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section BANK_0

public _fontCompressed
public _fontCompressed_end

_fontCompressed:

        BINARY "./output/binary/graphics/font-compressed.bin.zx0"

_fontCompressed_end:
