; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section BANK_0

public _fontCompressed
       _fontCompressed:
            BINARY "./output/asm/graphics/font-compressed.data.asm.zx0"
